#' Plot and Save IFCB PSD Data
#'
#' This function generates and saves data about a dataset's Particle Size Distribution (PSD) from Imaging FlowCytobot (IFCB)
#' feature and hdr files, which can be used for data quality assurance and quality control.
#'
#' @details
#' The PSD function originates from the `PSD` python repository (Hayashi et al. in prep), which can be found at \url{https://github.com/kudelalab/PSD}.
#' This function requires a python interpreter to be installed. The required python packages can be installed in a virtual environment using `ifcb_py_install`.
#' The function requires v2 features generated by the `ifcb-analysis` MATLAB package (Sosik and Olson 2007) found at \url{https://github.com/hsosik/ifcb-analysis}.
#'
#' @param feature_folder The absolute path to a directory containing all of the v2 feature files for the dataset.
#' @param hdr_folder The absolute path to a directory containing all of the hdr files for the dataset.
#' @param plot_folder The folder where graph images for each file will be saved. Set to NULL to not save graphs (default).
#' @param use_marker A boolean indicating whether to show markers on the plot. Default is FALSE.
#' @param start_fit An integer indicating the start fit value for the plot. Default is 10.
#' @param name A string with the base file name for the .csv to use (including path).
#' @param r_sqr The lower limit of acceptable R^2 values (any curves below it will be flagged). Default is 0.5.
#' @param beads The maximum multiplier for the curve fit. Any files with higher curve fit multipliers will be flagged as bead runs. If this argument is included, files with "runBeads" marked as TRUE in the header file will also be flagged as a bead run. Optional.
#' @param bubbles The minimum difference between the starting ESD and the ESD with the most targets.  Any files with a difference higher than this threshold will be flagged as mostly bubbles. Optional.
#' @param incomplete A tuple with the minimum volume of cells (in c/L) and the minimum mL analyzed for a complete run. Any files with values below these thresholds will be flagged as incomplete. Optional.
#' @param missing_cells The minimum image count to trigger count ratio. Any files with lower ratios will be flagged as missing cells. Optional.
#' @param biomass The minimum number of targets in the most populated ESD bin for any given run. Any files with fewer targets will be flagged as having low biomass. Optional.
#' @param bloom The minimum difference between the starting ESD and the ESD with the most targets. Any files with a difference less than this threshold will be flagged as a bloom. Will likely be lower than the bubbles threshold. Optional.
#' @param humidity The maximum percent humidity. Any files with higher values will be flagged as high humidity. Optional.
#'
#' @return This function does not return any value; it generates and saves the PSD data.
#' @seealso \code{\link{ifcb_py_install}} \url{https://github.com/kudelalab/PSD} \url{https://github.com/hsosik/ifcb-analysis}
#' @references Hayashi, K., Walton, J., Lie, A., Smith, J. and Kudela M. Using particle size distribution (PSD) to automate imaging flow cytobot (IFCB) data quality in coastal California, USA. In prep.
#' @references Sosik, H. M. and Olson, R. J. (2007) Limnol. Oceanogr: Methods 5, 204–216.
#' @import reticulate
#' @examples
#' \dontrun{
#' ifcb_psd(
#'   feature_folder = 'path/to/features',
#'   hdr_folder = 'path/to/hdr_data',
#'   plot_folder = 'psd/plots',
#'   use_marker = FALSE,
#'   start_fit = 10,
#'   name = 'psd/svea_2021',
#'   r_sqr = 0.5,
#'   beads = 10 ** 20,
#'   bubbles = 150,
#'   incomplete = c(1500, 3),
#'   missing_cells = 0.7,
#'   biomass = 1000,
#'   bloom = 5,
#'   humidity = NULL
#' )
#' }
#' @export
ifcb_psd <- function(feature_folder, hdr_folder, plot_folder = NULL, use_marker = FALSE, start_fit = 10,
                     name, r_sqr = 0.5, beads = NULL, bubbles = NULL, incomplete = NULL,
                     missing_cells = NULL, biomass = NULL, bloom = NULL, humidity = NULL) {

  # Ensure the iRfcb virtual environment is installed and used
  ifcb_py_install()
  .onLoad()

  # Set the path to the directory containing psd.py
  python_path <- system.file("python", package = "iRfcb")

  # Set the Python path to include the directory containing psd.py
  reticulate::py_run_string(paste0("import sys; sys.path.append('", python_path, "')"))

  # Import the PSD module
  PSD <- reticulate::import("psd")
  Bin <- PSD$Bin

  # Create a Bin object
  b <- Bin(feature_dir = feature_folder, hdr_dir = hdr_folder)

  # Plot the PSD
  b$plot_PSD(use_marker = use_marker, plot_folder = plot_folder, start_fit = as.integer(start_fit))

  # Prepare arguments for save_data
  args <- list(name = name, r_sqr = r_sqr)
  if (!is.null(beads)) args$beads <- as.numeric(beads)
  if (!is.null(bubbles)) args$bubbles <- as.integer(bubbles)
  if (!is.null(incomplete)) args$incomplete <- as.integer(incomplete)
  if (!is.null(missing_cells)) args$missing_cells <- missing_cells
  if (!is.null(biomass)) args$biomass <- as.integer(biomass)
  if (!is.null(bloom)) args$bloom <- as.integer(bloom)
  if (!is.null(humidity)) args$humidity <- humidity

  # Save the data
  do.call(b$save_data, args)
}
