#' Create a Manual Classification MAT File
#'
#' Generates a `.mat` file for IFCB data with classification structure using a specified number of ROIs
#' and class names. The `output_file` generated by this function is
#' compatible with the code in the `ifcb-analysis` repository (Sosik and Olson 2007).
#'
#' @param roi_length Integer. The number of rows in the class list (number of ROIs).
#' @param class2use Character vector. The names of the classes to include in the `class2use_manual` field of the MAT file.
#' @param output_file Character. The path where the output MAT file will be saved.
#' @param classlist Integer or numeric vector.
#'   Defines the values for the second column of the class list, typically representing the manual classification labels:
#'   - If a single value is provided, all rows will be assigned this value. For example, all ROIs can be assigned to class index 1 (default), which typically represents the unclassified category.
#'   - If a numeric vector of the same length as `roi_length` is provided, the corresponding values will be used per row.
#' @param do_compression A logical value indicating whether to compress the .mat file. Default is TRUE.
#'
#' @details
#' The MAT file is written directly from R, producing output identical to the
#' MATLAB `ifcb-analysis` format.
#'
#' @return No return value. This function is called for its side effects.
#' The created MAT file is saved at the specified `output_file` location.
#'
#' @examples
#' \dontrun{
#' # Create a MAT file with 100 ROIs, using a vector of class names, and save it to "output.mat"
#' ifcb_create_manual_file(roi_length = 100,
#'                         class2use = c("unclassified", "Aphanizomenon_spp"),
#'                         output_file = "output.mat")
#'
#' # Create a MAT file with 50 unclassified ROIs (1) and 50 Aphanizomenon_spp (2) ROIs
#' ifcb_create_manual_file(roi_length = 100,
#'                         class2use = c("unclassified", "Aphanizomenon_spp"),
#'                         output_file = "output.mat",
#'                         classlist = c(rep(1, 50), rep(2, 50)))
#' }
#'
#' @references Sosik, H. M. and Olson, R. J. (2007), Automated taxonomic classification of phytoplankton sampled with imaging-in-flow cytometry. Limnol. Oceanogr: Methods 5, 204–216.
#' @export
ifcb_create_manual_file <- function(roi_length, class2use, output_file, classlist = 1, do_compression = TRUE) {

  roi_length <- as.integer(roi_length)

  # Build the second column (manual classification) of the classlist:
  # a single value is broadcast, a vector must match roi_length
  if (length(classlist) == 1) {
    col2 <- rep(as.double(classlist), roi_length)
  } else if (length(classlist) == roi_length) {
    col2 <- as.double(classlist)
  } else {
    cli_abort("Length of {.arg classlist} ({length(classlist)}) must be 1 or equal to {.arg roi_length} ({roi_length}).")
  }

  # classlist columns: ROI number, manual classification, auto classification (NaN)
  classlist_mat <- cbind(
    as.double(seq_len(roi_length)),
    col2,
    rep(NaN, roi_length)
  )

  # Check if the output directory exists, if not create it
  if (!dir.exists(dirname(output_file))) {
    dir.create(dirname(output_file), recursive = TRUE)
  }

  # Assemble the structure expected by ifcb-analysis and write it
  write_mat_v5(
    output_file,
    list(
      class2use_manual = mat_var_cell(matrix(as.character(class2use), nrow = 1)),
      class2use_auto = mat_var_double(matrix(numeric(0), 0, 0)),
      classlist = mat_var_double(classlist_mat),
      list_titles = mat_var_cell(matrix(c("roi number", "manual", "auto"), nrow = 1)),
      default_class_original = mat_var_cell(matrix("unclassified", 1, 1))
    ),
    do_compression = do_compression
  )
}
