utils::globalVariables(c("biovolume"))
#' Extract biovolumes from IFCB data and compute carbon content
#'
#' This function reads biovolume data from feature files generated by the `ifcb-analysis` repository (Sosik and Olson 2007)
#' and matches them with corresponding classification results. It calculates biovolume in cubic micrometer and
#' determines if each class is a diatom based World Register of Marine Species (WoRMS). Carbon content
#' is computed for each roi using specific conversion functions depending on whether the class
#' is identified as a diatom or not, according to Menden-Deuer and Lessard 2000.
#'
#' @param feature_folder Path to the folder containing feature files.
#' @param class_folder Path to the folder containing class files.
#' @param micron_factor Conversion factor for biovolume to cubic microns. Default is 1 / 3.4.
#' @param diatom_class A string vector of diatom class names in the World Register of Marine Species (WoRMS). Default is "Bacillariophyceae".
#' @param threshold Threshold for selecting class information ("opt" or other, default is "opt").
#' @param multiblob A logical indicating whether to include multiblob features. Default is FALSE.
#'
#' @return A data frame containing sample, roi_number, class, biovolume_um3, and computed carbon_pg.
#'
#' @details
#' The function combines biovolume data extracted from feature files with class
#' information read from corresponding class files. It determines if each class is a
#' diatom based on user-defined criteria and computes carbon content using conversion
#' functions specific to diatoms and non-diatom protists.
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' feature_folder <- "data/features"
#' class_folder <- "data/classified"
#' biovolume_df <- ifcb_extract_biovolumes(feature_folder, class_folder)
#' print(biovolume_df)
#' }
#'
#' @references Menden-Deuer Susanne, Lessard Evelyn J., (2000), Carbon to volume relationships for dinoflagellates, diatoms, and other protist plankton, Limnology and Oceanography, 3, doi: 10.4319/lo.2000.45.3.0569.
#' @references Sosik, H. M. and Olson, R. J. (2007), Automated taxonomic classification of phytoplankton sampled with imaging-in-flow cytometry. Limnol. Oceanogr: Methods 5, 204–216.
#'
#' @importFrom R.matlab readMat
#' @importFrom dplyr left_join mutate case_when select
#' @importFrom stringr str_replace
#' @export
#'
#' @seealso \code{\link{ifcb_read_features}} \code{\link{ifcb_is_diatom}} \url{https://www.marinespecies.org/}
ifcb_extract_biovolumes <- function(feature_folder, class_folder, micron_factor = 1 / 3.4, diatom_class = "Bacillariophyceae", threshold = "opt", multiblob = FALSE) {
  features <- ifcb_read_features(feature_folder, multiblob = multiblob)
  classes <- list.files(class_folder, pattern = "D.*\\.mat", full.names = TRUE, recursive = TRUE)

  # Initialize an empty list to store data frames
  data_list <- list()

  # Loop through each feature file
  for (file_name in names(features)) {
    file_data <- features[[file_name]]

    # Create a data frame with sample, roi_number, and biovolume
    temp_df <- data.frame(
      sample = ifelse(multiblob, str_replace(file_name, "_multiblob_v\\d+.csv", ""), str_replace(file_name, "_fea_v\\d+.csv", "")),
      roi_number = file_data$roi_number,
      biovolume = file_data$Biovolume
    )

    # Append to the list
    data_list <- append(data_list, list(temp_df))
  }

  # Combine all data frames into one
  biovolume_df <- do.call(rbind, data_list)

  # Find unique samples in biovolume_df
  unique_samples <- unique(biovolume_df$sample)

  # Function to check if any sample name is in the class path
  contains_sample <- function(class_path, samples) {
    any(sapply(samples, grepl, class_path))
  }

  # Filter classes where the sample name exists in biovolume_df$sample
  matching_classes <- classes[sapply(classes, contains_sample, samples = unique_samples)]

  # Initialize an empty list to store data frames
  tb_list <- list()

  # Initialize a list to store all warnings
  warning_list <- list()

  # Loop through matching classes
  for (class in seq_along(matching_classes)) {
    # Capture warnings for each readMat call
    temp <- suppressWarnings({
      temp_result <- readMat(matching_classes[class])
      warning_list <- c(warning_list, warnings())
      temp_result
    })

    # Create a data frame with sample, roi_number, and class information
    temp_df <- data.frame(
      sample = str_replace(basename(matching_classes[class]), "_class_v\\d+.mat", ""),
      roi_number = temp$roinum,
      class = if (threshold == "opt") {
        unlist(temp$TBclass.above.threshold)
      } else {
        unlist(temp$TBclass)
      }
    )

    # Append to the list
    tb_list <- append(tb_list, list(temp_df))
  }

  # Display the number of warnings
  num_warnings <- length(warning_list)

  if (num_warnings > 0) {
    message(sprintf("There were %d warnings (use warnings() to see them)", num_warnings))
  }

  # Combine all data frames into one
  class_df <- do.call(rbind, tb_list)

  # Join biovolume_df with class_df
  biovolume_df <- left_join(biovolume_df, class_df, by = c("sample", "roi_number"))

  # Calculate biovolume in cubic microns
  biovolume_df$biovolume_um3 <- biovolume_df$biovolume * (micron_factor ^ 3)

  # Determine if each class is a diatom
  unique_classes <- unique(biovolume_df$class)
  is_diatom <- data.frame(class = unique_classes, is_diatom = ifcb_is_diatom(unique_classes, diatom_class = diatom_class))
  biovolume_df <- left_join(biovolume_df, is_diatom, by = "class")

  # Filter rows where is_diatom$is_diatom is NA
  na_classes <- is_diatom[is.na(is_diatom$is_diatom), "class"]

  # Filter rows where is_diatom$is_diatom is NA
  non_diatoms <- is_diatom[!is_diatom$is_diatom, "class"]

  # Print the classes with NA values
  if (length(na_classes) > 0) {
    cat("INFO: Some classes could not be found in WoRMS. They will be assumed as NOT diatoms for carbon calculations:\n")
    cat(sort(na_classes), sep = "\n")
  }

  # Print the classes that are non-Diatoms
  if (length(non_diatoms) > 0) {
    cat("INFO: The following classes are considered NOT diatoms for carbon calculations:\n")
    cat(sort(non_diatoms), sep = "\n")
  }

  # Calculate carbon content based on diatom classification
  biovolume_df <- biovolume_df %>%
    mutate(carbon_pg = case_when(
      !is.na(is_diatom) & is_diatom ~ vol2C_lgdiatom(biovolume_um3),
      !is.na(is_diatom) & !is_diatom ~ vol2C_nondiatom(biovolume_um3),
      is.na(is_diatom) ~ vol2C_nondiatom(biovolume_um3),
      TRUE ~ NA_real_
    )) %>%
    select(-biovolume, -is_diatom)

  return(biovolume_df)
}
