utils::globalVariables(c("biovolume_um3", "carbon_pg", "counts", "."))
#' Summarize biovolumes and carbon content from IFCB data
#'
#' This function calculates aggregated biovolumes and carbon content from Imaging FlowCytobot (IFCB)
#' samples based on feature and MATLAB classification result files, generated by the code in `ifcb-analysis`
#' repository (Sosik and Olson 2007). Biovolumes are converted to carbon according to Menden-Deuer and Lessard 2000
#' for individual regions of interest (ROI), where different conversion factors are applied to diatoms and
#' non-diatom protist. If provided, it also incorporates sample volume data from HDR files to compute
#' biovolume and carbon content per liter of sample.
#'
#' @param feature_folder Path to the folder containing feature files (e.g., CSV format).
#' @param class_folder Path to the folder containing class files (e.g., MATLAB MAT format).
#' @param hdr_folder Path to the folder containing HDR files (optional).
#' @param micron_factor Conversion factor from microns per pixel (default: 1/3.4).
#' @param diatom_class A string vector of diatom class names in the World Register of Marine Species (WoRMS). Default is "Bacillariophyceae".
#' @param threshold Threshold for classification (default: "opt").
#'
#' @return A data frame summarizing aggregated biovolume and carbon content per class per sample.
#'   Columns include 'sample', 'class', 'biovolume_mm3', 'carbon_ug', 'ml_analyzed',
#'   'biovolume_mm3_per_liter', and 'carbon_ug_per_liter'.
#'
#' @details This function performs the following steps:
#'   1. Extracts biovolumes and carbon content from feature and class files using `ifcb_extract_biovolumes`.
#'   2. Optionally incorporates volume data from HDR files to calculate volume analyzed per sample.
#'   3. Computes biovolume and carbon content per liter of sample analyzed.
#'
#' @examples
#' \dontrun{
#' # Example usage:
#' ifcb_summarize_biovolumes("path/to/features", "path/to/class", hdr_folder = "path/to/hdr")
#' }
#'
#' @references Menden-Deuer Susanne, Lessard Evelyn J., (2000), Carbon to volume relationships for dinoflagellates, diatoms, and other protist plankton, Limnology and Oceanography, 3, doi: 10.4319/lo.2000.45.3.0569.
#' @references Sosik, H. M. and Olson, R. J. (2007), Automated taxonomic classification of phytoplankton sampled with imaging-in-flow cytometry. Limnol. Oceanogr: Methods 5, 204–216.
#'
#' @importFrom dplyr group_by summarise left_join %>%
#'
#' @export
ifcb_summarize_biovolumes <- function(feature_folder, class_folder, hdr_folder = NULL, micron_factor = 1 / 3.4, diatom_class = "Bacillariophyceae", threshold = "opt") {

  # Step 1: Extract biovolumes and carbon content from feature and class files
  biovolumes <- ifcb_extract_biovolumes(feature_folder = feature_folder,
                                        class_folder = class_folder,
                                        micron_factor = micron_factor,
                                        diatom_class = diatom_class,
                                        threshold = threshold)

  # Step 2: Aggregate biovolumes and carbon content by sample and class
  biovolume_aggregated <- biovolumes %>%
    group_by(sample, class) %>%
    summarise(counts = n(),
              biovolume_mm3 = sum(biovolume_um3 * 10^-9, na.rm = TRUE),  # Convert from um3 to mm3
              carbon_ug = sum(carbon_pg * 10^-6, na.rm = TRUE),  # Convert from pg to ug
              .groups = 'drop')

  # Step 3: Optionally incorporate volume data from HDR files if provided
  if (!is.null(hdr_folder)) {
    class_files <- list.files(class_folder, pattern = "D.*\\.mat", full.names = TRUE, recursive = TRUE)
    hdr_files <- list.files(hdr_folder, pattern = "D.*\\.hdr", full.names = TRUE, recursive = TRUE)

    # Extract sample names from HDR and class files using a general regular expression
    hdr_sample_names <- sub(".*/(D\\d+T\\d+_IFCB\\d+)\\.hdr", "\\1", hdr_files)
    class_sample_names <- sub(".*/(D\\d+T\\d+_IFCB\\d+)_class_[a-zA-Z0-9_]+\\.mat", "\\1", class_files)

    # Find common sample names between HDR and class files
    common_sample_names <- intersect(hdr_sample_names, class_sample_names)

    # Filter HDR files to include only those matching common sample names
    hdr_files_filtered <- hdr_files[hdr_sample_names %in% common_sample_names]

    # Initialize an empty data frame to store volume data
    volumes <- data.frame()

    # Loop through filtered HDR files to extract volume analyzed per sample
    for (file in seq_along(hdr_files_filtered)) {
      volume <- data.frame(sample = sub(".*/(D\\d+T\\d+_IFCB\\d+)\\.hdr", "\\1", hdr_files_filtered[file]),
                           ml_analyzed = ifcb_volume_analyzed(hdr_files_filtered[file]))  # Calculate volume analyzed

      volumes <- rbind(volumes, volume)  # Append volume data to 'volumes' data frame
    }

    # Join volume data with aggregated biovolumes based on 'sample' column
    biovolume_aggregated <- left_join(biovolume_aggregated, volumes, by = "sample")

    # Calculate biovolume and carbon content per liter of sample analyzed
    biovolume_aggregated$counts_per_liter <- biovolume_aggregated$counts / (biovolume_aggregated$ml_analyzed / 1000)
    biovolume_aggregated$biovolume_mm3_per_liter <- biovolume_aggregated$biovolume_mm3 / (biovolume_aggregated$ml_analyzed / 1000)
    biovolume_aggregated$carbon_ug_per_liter <- biovolume_aggregated$carbon_ug / (biovolume_aggregated$ml_analyzed / 1000)
  }
  return(biovolume_aggregated)
}
